# Generated by Django 4.2.1 on 2023-05-22 09:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
