# Generated by Django 4.2.1 on 2023-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(max_length=128)),
                ('Calories', models.IntegerField(blank=True, null=True)),
                ('Total_Fat', models.IntegerField(blank=True, null=True)),
                ('Sodium', models.IntegerField(blank=True, null=True)),
                ('Potassium', models.IntegerField(blank=True, null=True)),
                ('Total_Carbohydrate', models.IntegerField(blank=True, null=True)),
                ('Dietary_Fiber', models.IntegerField(blank=True, null=True)),
                ('Protein', models.IntegerField(blank=True, null=True)),
                ('Vitamin_A', models.IntegerField(blank=True, null=True)),
                ('Vitamin_C', models.IntegerField(blank=True, null=True)),
                ('Calcium', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
