# Generated by Django 4.1.7 on 2023-04-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client3',
            new_name='Client',
        ),
    ]
