# Generated by Django 4.1.7 on 2023-04-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0002_rename_client3_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='guuid',
            new_name='id',
        ),
    ]
