# Generated by Django 4.1.7 on 2023-04-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0004_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='ramsize',
            new_name='ram_size',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='romsize',
            new_name='rom_size',
        ),
    ]
