# Generated by Django 4.1.7 on 2023-03-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
    ]
