# Generated by Django 4.1.7 on 2023-03-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2reg', '0004_user1_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='password',
        ),
    ]
