# Generated by Django 4.1.7 on 2023-03-26 05:26

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app2reg', '0007_user3'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('guuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Example: +8801XXXXXXXXX', max_length=14, region='BD')),
                ('image_url', models.URLField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
